version: "3.7"

volumes:
  pg_data:
    external: true

services: 
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: toor
      POSTGRES_USER: root
      POSTGRES_DB: blog_strapi_api
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'